apiVersion: v1
kind: Service
metadata:
  name: yelp-service
spec:
  selector:
    app: yelpcon
  ports:
  - protocol: "TCP"
    port: 8051
    targetPort: 7474
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelpdeploy
spec:
  selector:
    matchLabels:
      app: yelpcon
  replicas: 5
  template:
    metadata:
      labels:
        app: yelpcon
    spec:
      containers:
      - name: yelpcon
        image: sowmyakuruba/yelp:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7474